const menuData = [
  {
    id: "res-meghna-foods-123",
    info: {
      resName: "Meghna Foods",
      resRating: 4.5,
      ratingsCount: 2300,
      startPrice: "Starts at Just Rs.99/-",
      deliveryTime: 30,
      deliveryCharges: 30,
      cuisineType: ["North Indian", "Biryani", "Snacks"],
      availability: true,
      location: {
        city: "Hyderabad",
        area: "Madhapur",
        pincode: "500081",
      },
      logoUrl: "https://example.com/logos/meghna-foods.png",
    },
    offers: [
      {
        title: "50% off on order above 499/-",
        offerId: "123@off1",
      },
      {
        title: "Flat 30% off on all orders",
        offerId: "123@off2",
      },
    ],
    menuList: [
      {
        name: "Chicken Biryani",
        price: 199,
        itemId: "MF-1",
        img: "https://www.licious.in/blog/wp-content/uploads/2022/06/chicken-biryani-awadhi-01.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 872,
      },
      {
        name: "Paneer Butter Masala",
        price: 179,
        itemId: "MF-2",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSU2GVSX6yMjCLHtHBaQwyqjUw1rkC1sF9H8g&s",
        isVeg: true,
        rating: 4.5,
        ratingCount: 764,
      },
      {
        name: "Mutton Rogan Josh",
        price: 249,
        itemId: "MF-3",
        img: "https://static.toiimg.com/thumb/53192600.cms?width=1200&height=900",
        isVeg: false,
        rating: 4.4,
        ratingCount: 612,
      },
      {
        name: "Veg Pulao",
        price: 129,
        itemId: "MF-4",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXh8JwS9wEk8r2un31eZJtUqoEIveNLTHibg&s",
        isVeg: true,
        rating: 4.3,
        ratingCount: 495,
      },
      {
        name: "Dal Makhani",
        price: 149,
        itemId: "MF-5",
        img: "https://www.funfoodfrolic.com/wp-content/uploads/2023/04/Dal-Makhani-Blog-500x375.jpg",
        isVeg: true,
        rating: 4.7,
        ratingCount: 823,
      },
      {
        name: "Tandoori Chicken",
        price: 229,
        itemId: "MF-6",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLUBD5UmZsAvHINIfElUJ4X0FqFlkbYQoy5Q&s",
        isVeg: false,
        rating: 4.5,
        ratingCount: 710,
      },
      {
        name: "Butter Naan",
        price: 39,
        itemId: "MF-7",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJbhIBt1bfid1hVKLprQyN3Xd31fHVTyfmKg&s",
        isVeg: true,
        rating: 4.2,
        ratingCount: 432,
      },
      {
        name: "Garlic Naan",
        price: 49,
        itemId: "MF-8",
        img: "https://www.vegrecipesofindia.com/wp-content/uploads/2022/12/garlic-naan-3.jpg",
        isVeg: true,
        rating: 4.4,
        ratingCount: 508,
      },
      {
        name: "Chicken Tikka Masala",
        price: 219,
        itemId: "MF-9",
        img: "https://bellyfull.net/wp-content/uploads/2021/05/Chicken-Tikka-Masala-blog.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 795,
      },
      {
        name: "Palak Paneer",
        price: 159,
        itemId: "MF-10",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_I8R5TXGoabQURaYGUMiLe7d1GIcdpLdTLQ&s",
        isVeg: true,
        rating: 4.5,
        ratingCount: 684,
      },
      {
        name: "Chole Bhature",
        price: 119,
        itemId: "MF-11",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSHuqEQvNy--dkfLm4j4WW74dgvb2tb4HilQ&s",
        isVeg: true,
        rating: 4.4,
        ratingCount: 577,
      },
      {
        name: "Rajma Chawal",
        price: 109,
        itemId: "MF-12",
        img: "https://i0.wp.com/www.hmbsweets.com/wp-content/uploads/2025/04/img_8270.jpeg?fit=1290%2C1166&ssl=1",
        isVeg: true,
        rating: 4.3,
        ratingCount: 519,
      },
      {
        name: "Fish Curry",
        price: 239,
        itemId: "MF-13",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSR5bv5CUtCfSyCjiwS29HyMoq0FfaCTGxX1A&s",
        isVeg: false,
        rating: 4.4,
        ratingCount: 611,
      },
      {
        name: "Egg Curry",
        price: 139,
        itemId: "MF-14",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxTqU86t6JpM6rmAuWZuf4uZCGRLcK-_iNXw&s",
        isVeg: false,
        rating: 4.2,
        ratingCount: 407,
      },
      {
        name: "Kadai Paneer",
        price: 169,
        itemId: "MF-15",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9yNlUSNyvZYmrS3UfdN8R3kkJVMh4nzM7nQ&s",
        isVeg: true,
        rating: 4.6,
        ratingCount: 733,
      },
      {
        name: "Chicken Korma",
        price: 209,
        itemId: "MF-16",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUadSrrPDNrkBE4NWndPQrikziWUnKfGYMlg&s",
        isVeg: false,
        rating: 4.5,
        ratingCount: 691,
      },
      {
        name: "Aloo Gobi",
        price: 99,
        itemId: "MF-17",
        img: "https://niksharmacooks.com/wp-content/uploads/2022/11/AlooGobiDSC_5234.jpg",
        isVeg: true,
        rating: 4.3,
        ratingCount: 465,
      },
      {
        name: "Jeera Rice",
        price: 89,
        itemId: "MF-18",
        img: "https://myfoodstory.com/wp-content/uploads/2018/07/Perfect-Jeera-Rice-Indian-Cumin-Rice-4-500x500.jpg",
        isVeg: true,
        rating: 4.2,
        ratingCount: 382,
      },
      {
        name: "Malai Kofta",
        price: 189,
        itemId: "MF-19",
        img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/06/malai-kofta-recipe.jpg",
        isVeg: true,
        rating: 4.7,
        ratingCount: 821,
      },
      {
        name: "Hyderabadi Biryani",
        price: 219,
        itemId: "MF-20",
        img: "https://images.herzindagi.info/image/2018/Oct/biryani-delhi-main.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 889,
      },
      {
        name: "Mix Veg Curry",
        price: 139,
        itemId: "MF-21",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhFmMGJlfxGvp0zGmsGjUijCWxynckzwvYfQ&s",
        isVeg: true,
        rating: 4.4,
        ratingCount: 550,
      },
    ],
  },
  {
    id: "res-kfc-124",
    info: {
      resName: "KFC",
      resRating: 4.2,
      ratingsCount: 1480,
      startPrice: "Starts at Just Rs.149/-",
      deliveryTime: 25,
      deliveryCharges: 40,
      cuisineType: ["Burger", "Fast Food", "Mughlai", "Tandoori"],
      availability: true,
      location: {
        city: "Delhi",
        area: "Connaught Place",
        pincode: "110001",
      },
      logoUrl: "https://example.com/logos/tandoori-tales.png",
    },
    offers: [
      {
        title: "Flat 30% off on all orders",
        offerId: "kfc@1",
      },
    ],
    menuList: [
      {
        name: "Zinger Burger",
        price: 149,
        itemId: "KFC-1",
        img: "https://images.kfcpakistan.com/image/1671104996573-image.jpg",
        isVeg: false,
        rating: 4.5,
        ratingCount: 814,
      },
      {
        name: "Hot Wings (6 pcs)",
        price: 199,
        itemId: "KFC-2",
        img: "https://images.kfcpakistan.com/image/1671104930034-image.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 725,
      },
      {
        name: "Chicken Popcorn",
        price: 149,
        itemId: "KFC-3",
        img: "https://images.kfcpakistan.com/image/1671104955242-image.jpg",
        isVeg: false,
        rating: 4.4,
        ratingCount: 602,
      },
      {
        name: "Veg Zinger Burger",
        price: 129,
        itemId: "KFC-4",
        img: "https://www.kfc.com.sg/Content/OnlineOrderingImages/Menu/Product/Detail/Veg-Zinger_1052.png",
        isVeg: true,
        rating: 4.1,
        ratingCount: 398,
      },
      {
        name: "Bucket Chicken (4 pcs)",
        price: 399,
        itemId: "KFC-5",
        img: "https://images.kfcpakistan.com/image/1671104922936-image.jpg",
        isVeg: false,
        rating: 4.7,
        ratingCount: 998,
      },
      {
        name: "Fries (Regular)",
        price: 79,
        itemId: "KFC-6",
        img: "https://images.kfcpakistan.com/image/1671105006495-image.jpg",
        isVeg: true,
        rating: 4.2,
        ratingCount: 478,
      },
      {
        name: "Pepsi (Medium)",
        price: 49,
        itemId: "KFC-7",
        img: "https://www.kfc.com.sg/Content/OnlineOrderingImages/Menu/Product/Detail/Pepsi_1060.png",
        isVeg: true,
        rating: 4.0,
        ratingCount: 312,
      },
      {
        name: "Chocolate Lava Cake",
        price: 89,
        itemId: "KFC-8",
        img: "https://images.kfcpakistan.com/image/1671105103760-image.jpg",
        isVeg: true,
        rating: 4.6,
        ratingCount: 645,
      },
      {
        name: "Twister Wrap",
        price: 189,
        itemId: "KFC-9",
        img: "https://images.kfcpakistan.com/image/1671104981126-image.jpg",
        isVeg: false,
        rating: 4.3,
        ratingCount: 528,
      },
      {
        name: "Peri Peri Chicken",
        price: 229,
        itemId: "KFC-10",
        img: "https://images.kfcpakistan.com/image/1671104970299-image.jpg",
        isVeg: false,
        rating: 4.5,
        ratingCount: 589,
      },
    ],
  },
  {
    id: "res-dominos-125",
    info: {
      resName: "Dominos",
      resRating: 3.8,
      ratingsCount: 1210,
      startPrice: "Starts at Just Rs.129/-",
      deliveryTime: 20,
      deliveryCharges: 0,
      cuisineType: ["Italian", "Pizza", "Fast Food"],
      availability: false,
      location: {
        city: "Mumbai",
        area: "Andheri West",
        pincode: "400053",
      },
      logoUrl: "https://example.com/logos/pizza-villa.png",
    },
    offers: [
      {
        title: "Free Garlic Bread on orders above 399/-",
        offerId: "dom@1",
      },
    ],
    menuList: [
      {
        name: "Margherita Pizza",
        price: 179,
        itemId: "DOM-1",
        img: "https://images.dominos.co.in/new_margherita_2502.jpg",
        isVeg: true,
        rating: 4.4,
        ratingCount: 932,
      },
      {
        name: "Pepperoni Pizza",
        price: 269,
        itemId: "DOM-2",
        img: "https://images.dominos.co.in/pepperoni.jpg",
        isVeg: false,
        rating: 4.5,
        ratingCount: 1103,
      },
      {
        name: "Farmhouse Pizza",
        price: 249,
        itemId: "DOM-3",
        img: "https://images.dominos.co.in/farmhouse.png",
        isVeg: true,
        rating: 4.3,
        ratingCount: 856,
      },
      {
        name: "Chicken Dominator",
        price: 299,
        itemId: "DOM-4",
        img: "https://images.dominos.co.in/chickendominator.png",
        isVeg: false,
        rating: 4.6,
        ratingCount: 967,
      },
      {
        name: "Veggie Paradise",
        price: 239,
        itemId: "DOM-5",
        img: "https://images.dominos.co.in/veggie_paradise.png",
        isVeg: true,
        rating: 4.2,
        ratingCount: 734,
      },
      {
        name: "Indi Tandoori Paneer",
        price: 259,
        itemId: "DOM-6",
        img: "https://images.dominos.co.in/indi_tandoori_paneer.jpg",
        isVeg: true,
        rating: 4.5,
        ratingCount: 810,
      },
      {
        name: "Mexican Green Wave",
        price: 229,
        itemId: "DOM-7",
        img: "https://images.dominos.co.in/new_mexican_green_wave.jpg",
        isVeg: true,
        rating: 4.3,
        ratingCount: 655,
      },
      {
        name: "Cheese Burst Pizza",
        price: 279,
        itemId: "DOM-8",
        img: "https://images.dominos.co.in/cheese_burst.png",
        isVeg: true,
        rating: 4.6,
        ratingCount: 1182,
      },
      {
        name: "Paneer Makhani Pizza",
        price: 269,
        itemId: "DOM-9",
        img: "https://images.dominos.co.in/paneer_makhani.jpg",
        isVeg: true,
        rating: 4.4,
        ratingCount: 752,
      },
      {
        name: "Chicken Sausage Pizza",
        price: 249,
        itemId: "DOM-10",
        img: "https://images.dominos.co.in/chicken_sausage.jpg",
        isVeg: false,
        rating: 4.3,
        ratingCount: 634,
      },
      {
        name: "Chicken Tikka Pizza",
        price: 289,
        itemId: "DOM-11",
        img: "https://images.dominos.co.in/chicken_tikka.jpg",
        isVeg: false,
        rating: 4.5,
        ratingCount: 743,
      },
      {
        name: "Deluxe Veggie Pizza",
        price: 259,
        itemId: "DOM-12",
        img: "https://images.dominos.co.in/deluxe_veggie.jpg",
        isVeg: true,
        rating: 4.4,
        ratingCount: 812,
      },
      {
        name: "Pepper Barbecue Chicken Pizza",
        price: 279,
        itemId: "DOM-13",
        img: "https://images.dominos.co.in/pepper_barbeque_chicken.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 905,
      },
      {
        name: "Corn & Cheese Pizza",
        price: 219,
        itemId: "DOM-14",
        img: "https://images.dominos.co.in/corn_cheese.jpg",
        isVeg: true,
        rating: 4.2,
        ratingCount: 544,
      },
      {
        name: "Stuffed Garlic Bread",
        price: 129,
        itemId: "DOM-15",
        img: "https://images.dominos.co.in/stuffed_garlic_bread.jpg",
        isVeg: true,
        rating: 4.7,
        ratingCount: 1165,
      },
      {
        name: "Taco Mexicana (Veg)",
        price: 139,
        itemId: "DOM-16",
        img: "https://images.dominos.co.in/taco_mexicana_veg.jpg",
        isVeg: true,
        rating: 4.3,
        ratingCount: 693,
      },
      {
        name: "Choco Lava Cake",
        price: 99,
        itemId: "DOM-17",
        img: "https://images.dominos.co.in/choco_lava_cake.jpg",
        isVeg: true,
        rating: 4.8,
        ratingCount: 1348,
      },
      {
        name: "Butterscotch Mousse Cake",
        price: 99,
        itemId: "DOM-18",
        img: "https://images.dominos.co.in/butterscotch_mousse.jpg",
        isVeg: true,
        rating: 4.4,
        ratingCount: 598,
      },
      {
        name: "Paneer Parcel",
        price: 59,
        itemId: "DOM-19",
        img: "https://images.dominos.co.in/paneer_parcel.jpg",
        isVeg: true,
        rating: 4.2,
        ratingCount: 511,
      },
      {
        name: "Cold Drink (500ml)",
        price: 60,
        itemId: "DOM-20",
        img: "https://images.dominos.co.in/pepsi_500ml.jpg",
        isVeg: true,
        rating: 4.1,
        ratingCount: 407,
      },
    ],
  },
  {
    id: "res-biryani-house-126",
    info: {
      resName: "Biryani House",
      resRating: 3.4,
      ratingsCount: 980,
      startPrice: "Starts at Just Rs.59/-",
      deliveryTime: 35,
      deliveryCharges: 15,
      cuisineType: ["Biryani", "Fried Rice", "Snacks"],
      availability: true,
      location: {
        city: "Ahmedabad",
        area: "Navrangpura",
        pincode: "380009",
      },
      logoUrl: "https://example.com/logos/urban-chaat.png",
    },
    offers: [
      {
        title: "Buy 1 Get 1 Free on select items",
        offerId: "bh@1",
      },
    ],
    menuList: [
      {
        name: "Hyderabadi Chicken Biryani",
        price: 229,
        itemId: "BYR-1",
        img: "https://www.cubesnjuliennes.com/wp-content/uploads/2020/12/Hyderabadi-Chicken-Biryani-Recipe.jpg",
        isVeg: false,
        rating: 4.7,
        ratingCount: 1420,
      },
      {
        name: "Lucknowi Mutton Biryani",
        price: 259,
        itemId: "BYR-2",
        img: "https://www.whiskaffair.com/wp-content/uploads/2020/06/Lucknowi-Mutton-Biryani-2-3.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 1042,
      },
      {
        name: "Veg Biryani",
        price: 179,
        itemId: "BYR-3",
        img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/08/veg-biryani-recipe.jpg",
        isVeg: true,
        rating: 4.3,
        ratingCount: 798,
      },
      {
        name: "Paneer Biryani",
        price: 189,
        itemId: "BYR-4",
        img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/paneer-biryani-recipe.jpg",
        isVeg: true,
        rating: 4.4,
        ratingCount: 582,
      },
      {
        name: "Egg Biryani",
        price: 199,
        itemId: "BYR-5",
        img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/egg-biryani.jpg",
        isVeg: false,
        rating: 4.5,
        ratingCount: 679,
      },
      {
        name: "Kolkata Chicken Biryani",
        price: 239,
        itemId: "BYR-6",
        img: "https://www.whiskaffair.com/wp-content/uploads/2020/06/Kolkata-Biryani-2.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 963,
      },
      {
        name: "Andhra Spicy Chicken Biryani",
        price: 249,
        itemId: "BYR-7",
        img: "https://yummyindiankitchen.com/wp-content/uploads/2021/01/andhra-chicken-biryani-recipe.jpg",
        isVeg: false,
        rating: 4.7,
        ratingCount: 741,
      },
      {
        name: "Mughlai Biryani",
        price: 269,
        itemId: "BYR-8",
        img: "https://www.archanaskitchen.com/images/archanaskitchen/1-Author/sibyl/sibyl_mughlai_chicken_biryani.jpg",
        isVeg: false,
        rating: 4.8,
        ratingCount: 865,
      },
      {
        name: "Dum Aloo Biryani",
        price: 169,
        itemId: "BYR-9",
        img: "https://www.whiskaffair.com/wp-content/uploads/2020/06/Dum-Aloo-Biryani-2.jpg",
        isVeg: true,
        rating: 4.2,
        ratingCount: 442,
      },
      {
        name: "Fish Biryani",
        price: 259,
        itemId: "BYR-10",
        img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/07/fish-biryani-recipe.jpg",
        isVeg: false,
        rating: 4.4,
        ratingCount: 388,
      },
      {
        name: "Prawn Biryani",
        price: 269,
        itemId: "BYR-11",
        img: "https://www.whiskaffair.com/wp-content/uploads/2018/12/Prawns-Biryani-2-3.jpg",
        isVeg: false,
        rating: 4.5,
        ratingCount: 410,
      },
      {
        name: "Keema Biryani",
        price: 239,
        itemId: "BYR-12",
        img: "https://www.archanaskitchen.com/images/archanaskitchen/1-Author/Asha/Shahi_Keema_Biryani.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 364,
      },
      {
        name: "Double Masala Chicken Biryani",
        price: 249,
        itemId: "BYR-13",
        img: "https://www.cookwithmanali.com/wp-content/uploads/2020/11/Chicken-Biryani.jpg",
        isVeg: false,
        rating: 4.7,
        ratingCount: 601,
      },
      {
        name: "Jackfruit Biryani",
        price: 199,
        itemId: "BYR-14",
        img: "https://www.archanaskitchen.com/images/archanaskitchen/1-Author/asha/jackfruit_kathal_biryani.jpg",
        isVeg: true,
        rating: 4.3,
        ratingCount: 332,
      },
      {
        name: "Curd Raita",
        price: 39,
        itemId: "BYR-15",
        img: "https://www.vegrecipesofindia.com/wp-content/uploads/2015/05/boondi-raita-recipe-2.jpg",
        isVeg: true,
        rating: 4.6,
        ratingCount: 728,
      },
      {
        name: "Mirchi Ka Salan",
        price: 59,
        itemId: "BYR-16",
        img: "https://www.cookwithmanali.com/wp-content/uploads/2021/07/Mirchi-ka-Salan.jpg",
        isVeg: true,
        rating: 4.5,
        ratingCount: 405,
      },
      {
        name: "Biryani Combo (Veg)",
        price: 299,
        itemId: "BYR-17",
        img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/03/veg-biryani-combo.jpg",
        isVeg: true,
        rating: 4.4,
        ratingCount: 563,
      },
      {
        name: "Biryani Combo (Chicken)",
        price: 349,
        itemId: "BYR-18",
        img: "https://www.whiskaffair.com/wp-content/uploads/2022/07/Chicken-Biryani-Combo.jpg",
        isVeg: false,
        rating: 4.7,
        ratingCount: 795,
      },
      {
        name: "Soya Biryani",
        price: 189,
        itemId: "BYR-19",
        img: "https://www.vegrecipesofindia.com/wp-content/uploads/2015/11/soya-biryani-recipe.jpg",
        isVeg: true,
        rating: 4.2,
        ratingCount: 278,
      },
      {
        name: "Mini Chicken Biryani",
        price: 129,
        itemId: "BYR-20",
        img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/11/small-portions-biryani.jpg",
        isVeg: false,
        rating: 4.3,
        ratingCount: 501,
      },
      {
        name: "Afghani Chicken Biryani",
        price: 269,
        itemId: "BYR-21",
        img: "https://i.ytimg.com/vi/DUEKn1OgL3Y/maxresdefault.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 397,
      },
      {
        name: "Kaju Biryani",
        price: 229,
        itemId: "BYR-22",
        img: "https://www.vegrecipesofindia.com/wp-content/uploads/2019/04/kaju-biryani-recipe-1.jpg",
        isVeg: true,
        rating: 4.3,
        ratingCount: 319,
      },
      {
        name: "Dindigul Mutton Biryani",
        price: 259,
        itemId: "BYR-23",
        img: "https://www.ticklingpalates.com/wp-content/uploads/2020/08/dindigul-mutton-biryani.jpg",
        isVeg: false,
        rating: 4.5,
        ratingCount: 548,
      },
      {
        name: "Chicken 65 Biryani",
        price: 249,
        itemId: "BYR-24",
        img: "https://www.cookingcarnival.com/wp-content/uploads/2021/09/Chicken-65-Biryani-3.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 622,
      },
      {
        name: "Mushroom Biryani",
        price: 199,
        itemId: "BYR-25",
        img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/09/mushroom-biryani.jpg",
        isVeg: true,
        rating: 4.4,
        ratingCount: 438,
      },
    ],
  },
  {
    id: "res-burger-king-127",
    info: {
      resName: "Burger King",
      resRating: 4.2,
      ratingsCount: 1575,
      startPrice: "Starts at Just Rs.89/-",
      deliveryTime: 15,
      deliveryCharges: 20,
      cuisineType: ["Burger", "Fast Food"],
      availability: true,
      location: {
        city: "Chennai",
        area: "T Nagar",
        pincode: "600017",
      },
      logoUrl: "https://example.com/logos/south-spice.png",
    },
    offers: [
      {
        title: "20% off on orders above 299/-",
        offerId: "bk@1",
      },
    ],
    menuList: [
      {
        name: "Whopper",
        price: 229,
        itemId: "BK-1",
        img: "https://www.burgerking.in/StaticMenuImages/Whopper_Chicken_7.jpg",
        isVeg: false,
        rating: 4.7,
        ratingCount: 1502,
      },
      {
        name: "Veg Whopper",
        price: 199,
        itemId: "BK-2",
        img: "https://www.burgerking.in/StaticMenuImages/Whopper_Veg_7.jpg",
        isVeg: true,
        rating: 4.5,
        ratingCount: 1248,
      },
      {
        name: "Crispy Chicken Burger",
        price: 149,
        itemId: "BK-3",
        img: "https://www.burgerking.in/StaticMenuImages/CrispyChicken_7.jpg",
        isVeg: false,
        rating: 4.4,
        ratingCount: 1105,
      },
      {
        name: "Crispy Veg Burger",
        price: 129,
        itemId: "BK-4",
        img: "https://www.burgerking.in/StaticMenuImages/CrispyVeg_7.jpg",
        isVeg: true,
        rating: 4.3,
        ratingCount: 980,
      },
      {
        name: "Chicken Double Patty Burger",
        price: 189,
        itemId: "BK-5",
        img: "https://www.burgerking.in/StaticMenuImages/ChickenWhopperDouble_7.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 889,
      },
      {
        name: "Veg Double Patty Burger",
        price: 169,
        itemId: "BK-6",
        img: "https://www.burgerking.in/StaticMenuImages/VegWhopperDouble_7.jpg",
        isVeg: true,
        rating: 4.4,
        ratingCount: 812,
      },
      {
        name: "Fiery Chicken Burger",
        price: 199,
        itemId: "BK-7",
        img: "https://www.burgerking.in/StaticMenuImages/FieryChicken_7.jpg",
        isVeg: false,
        rating: 4.5,
        ratingCount: 756,
      },
      {
        name: "Paneer Royale Burger",
        price: 219,
        itemId: "BK-8",
        img: "https://www.burgerking.in/StaticMenuImages/PaneerRoyale_7.jpg",
        isVeg: true,
        rating: 4.5,
        ratingCount: 692,
      },
      {
        name: "Mutton Whopper",
        price: 259,
        itemId: "BK-9",
        img: "https://www.burgerking.in/StaticMenuImages/Whopper_Mutton_7.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 620,
      },
      {
        name: "Cheese Burger",
        price: 179,
        itemId: "BK-10",
        img: "https://www.burgerking.in/StaticMenuImages/CheeseBurger_7.jpg",
        isVeg: true,
        rating: 4.3,
        ratingCount: 588,
      },
      {
        name: "Chicken Tandoor Grill",
        price: 239,
        itemId: "BK-11",
        img: "https://www.burgerking.in/StaticMenuImages/Tandoor_Chicken_7.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 470,
      },
      {
        name: "French Fries (Medium)",
        price: 89,
        itemId: "BK-12",
        img: "https://www.burgerking.in/StaticMenuImages/Fries_M_7.jpg",
        isVeg: true,
        rating: 4.4,
        ratingCount: 1480,
      },
      {
        name: "French Fries (Large)",
        price: 109,
        itemId: "BK-13",
        img: "https://www.burgerking.in/StaticMenuImages/Fries_L_7.jpg",
        isVeg: true,
        rating: 4.5,
        ratingCount: 1321,
      },
      {
        name: "Onion Rings",
        price: 99,
        itemId: "BK-14",
        img: "https://www.burgerking.in/StaticMenuImages/Onion_Rings_7.jpg",
        isVeg: true,
        rating: 4.2,
        ratingCount: 1103,
      },
      {
        name: "Chicken Nuggets (6 pcs)",
        price: 129,
        itemId: "BK-15",
        img: "https://www.burgerking.in/StaticMenuImages/Nuggets6_7.jpg",
        isVeg: false,
        rating: 4.4,
        ratingCount: 972,
      },
      {
        name: "Chocolate Mousse Cup",
        price: 89,
        itemId: "BK-16",
        img: "https://www.burgerking.in/StaticMenuImages/Mousse_7.jpg",
        isVeg: true,
        rating: 4.5,
        ratingCount: 831,
      },
      {
        name: "Soft Drink (500ml)",
        price: 59,
        itemId: "BK-17",
        img: "https://www.burgerking.in/StaticMenuImages/Coke_7.jpg",
        isVeg: true,
        rating: 4.3,
        ratingCount: 1044,
      },
      {
        name: "Peri Peri Fries",
        price: 109,
        itemId: "BK-18",
        img: "https://www.burgerking.in/StaticMenuImages/PeriFries_7.jpg",
        isVeg: true,
        rating: 4.4,
        ratingCount: 998,
      },
      {
        name: "King Egg Burger",
        price: 149,
        itemId: "BK-19",
        img: "https://www.burgerking.in/StaticMenuImages/EggBurger_7.jpg",
        isVeg: false,
        rating: 4.2,
        ratingCount: 452,
      },
      {
        name: "Ice Cream Sundae",
        price: 89,
        itemId: "BK-20",
        img: "https://www.burgerking.in/StaticMenuImages/Sundae_7.jpg",
        isVeg: true,
        rating: 4.6,
        ratingCount: 738,
      },
      {
        name: "Tandoori Veg Burger",
        price: 159,
        itemId: "BK-21",
        img: "https://www.burgerking.in/StaticMenuImages/TandooriVeg_7.jpg",
        isVeg: true,
        rating: 4.4,
        ratingCount: 684,
      },
      {
        name: "Cheesy Italian Burger",
        price: 199,
        itemId: "BK-22",
        img: "https://www.burgerking.in/StaticMenuImages/Cheesy_Italian_7.jpg",
        isVeg: true,
        rating: 4.3,
        ratingCount: 543,
      },
      {
        name: "Cold Coffee",
        price: 109,
        itemId: "BK-23",
        img: "https://www.burgerking.in/StaticMenuImages/ColdCoffee_7.jpg",
        isVeg: true,
        rating: 4.4,
        ratingCount: 471,
      },
      {
        name: "Cheesy Fries",
        price: 129,
        itemId: "BK-24",
        img: "https://www.burgerking.in/StaticMenuImages/CheesyFries_7.jpg",
        isVeg: true,
        rating: 4.5,
        ratingCount: 598,
      },
      {
        name: "Classic Chicken Wrap",
        price: 159,
        itemId: "BK-25",
        img: "https://www.burgerking.in/StaticMenuImages/ChickenWrap_7.jpg",
        isVeg: false,
        rating: 4.5,
        ratingCount: 650,
      },
    ],
  },
  {
    id: "res-pizza-hut-128",
    info: {
      resName: "Pizza Hut",
      resRating: 3.8,
      ratingsCount: 2675,
      startPrice: "Starts at Just Rs.109/-",
      deliveryTime: 30,
      deliveryCharges: 35,
      cuisineType: ["Maharashtrian", "Street Food"],
      availability: false,
      location: {
        city: "Mumbai",
        area: "Borivali East",
        pincode: "400066",
      },
      logoUrl: "https://example.com/logos/mumbai-magic.png",
    },
    offers: [
      {
        title: "Flat 40% off on your first order",
        offerId: "ph@001",
      },
    ],
    menuList: [
      {
        name: "Margherita Pizza",
        price: 229,
        itemId: "PH-1",
        img: "https://www.pizzahut.co.in/order/images/products/margherita.png",
        isVeg: true,
        rating: 4.5,
        ratingCount: 1450,
      },
      {
        name: "Farmhouse Pizza",
        price: 299,
        itemId: "PH-2",
        img: "https://www.pizzahut.co.in/order/images/products/farmhouse.png",
        isVeg: true,
        rating: 4.6,
        ratingCount: 1378,
      },
      {
        name: "Chicken Tikka Pizza",
        price: 349,
        itemId: "PH-3",
        img: "https://www.pizzahut.co.in/order/images/products/chickentikka.png",
        isVeg: false,
        rating: 4.7,
        ratingCount: 1260,
      },
      {
        name: "Veggie Supreme Pizza",
        price: 319,
        itemId: "PH-4",
        img: "https://www.pizzahut.co.in/order/images/products/veggiesupreme.png",
        isVeg: true,
        rating: 4.5,
        ratingCount: 1132,
      },
      {
        name: "Paneer Tikka Pizza",
        price: 329,
        itemId: "PH-5",
        img: "https://www.pizzahut.co.in/order/images/products/paneertikka.png",
        isVeg: true,
        rating: 4.6,
        ratingCount: 1023,
      },
      {
        name: "Classic Corn Pizza",
        price: 259,
        itemId: "PH-6",
        img: "https://www.pizzahut.co.in/order/images/products/corn.png",
        isVeg: true,
        rating: 4.4,
        ratingCount: 980,
      },
      {
        name: "Cheese Lovers Pizza",
        price: 279,
        itemId: "PH-7",
        img: "https://www.pizzahut.co.in/order/images/products/cheeselovers.png",
        isVeg: true,
        rating: 4.5,
        ratingCount: 890,
      },
      {
        name: "Mexican Green Wave",
        price: 289,
        itemId: "PH-8",
        img: "https://www.pizzahut.co.in/order/images/products/mexican.png",
        isVeg: true,
        rating: 4.6,
        ratingCount: 870,
      },
      {
        name: "Pepperoni Pizza",
        price: 359,
        itemId: "PH-9",
        img: "https://www.pizzahut.co.in/order/images/products/pepperoni.png",
        isVeg: false,
        rating: 4.7,
        ratingCount: 950,
      },
      {
        name: "Chicken Sausage Pizza",
        price: 339,
        itemId: "PH-10",
        img: "https://www.pizzahut.co.in/order/images/products/chickensausage.png",
        isVeg: false,
        rating: 4.5,
        ratingCount: 830,
      },
      {
        name: "Tandoori Paneer Pizza",
        price: 309,
        itemId: "PH-11",
        img: "https://www.pizzahut.co.in/order/images/products/tandooripaneer.png",
        isVeg: true,
        rating: 4.5,
        ratingCount: 780,
      },
      {
        name: "Triple Chicken Feast",
        price: 379,
        itemId: "PH-12",
        img: "https://www.pizzahut.co.in/order/images/products/triplechicken.png",
        isVeg: false,
        rating: 4.7,
        ratingCount: 720,
      },
      {
        name: "Garlic Breadsticks",
        price: 109,
        itemId: "PH-13",
        img: "https://www.pizzahut.co.in/order/images/products/garlicbread.png",
        isVeg: true,
        rating: 4.6,
        ratingCount: 1320,
      },
      {
        name: "Stuffed Garlic Bread",
        price: 139,
        itemId: "PH-14",
        img: "https://www.pizzahut.co.in/order/images/products/stuffedbread.png",
        isVeg: true,
        rating: 4.5,
        ratingCount: 980,
      },
      {
        name: "Chicken Wings (6 pcs)",
        price: 199,
        itemId: "PH-15",
        img: "https://www.pizzahut.co.in/order/images/products/chickenwings.png",
        isVeg: false,
        rating: 4.6,
        ratingCount: 900,
      },
      {
        name: "Choco Lava Cake",
        price: 99,
        itemId: "PH-16",
        img: "https://www.pizzahut.co.in/order/images/products/lavacake.png",
        isVeg: true,
        rating: 4.8,
        ratingCount: 1150,
      },
      {
        name: "Veggie Pasta",
        price: 179,
        itemId: "PH-17",
        img: "https://www.pizzahut.co.in/order/images/products/veg_pasta.png",
        isVeg: true,
        rating: 4.3,
        ratingCount: 670,
      },
      {
        name: "Chicken Pasta",
        price: 199,
        itemId: "PH-18",
        img: "https://www.pizzahut.co.in/order/images/products/chicken_pasta.png",
        isVeg: false,
        rating: 4.4,
        ratingCount: 640,
      },
      {
        name: "Cold Coffee",
        price: 99,
        itemId: "PH-19",
        img: "https://www.pizzahut.co.in/order/images/products/coldcoffee.png",
        isVeg: true,
        rating: 4.2,
        ratingCount: 720,
      },
      {
        name: "Pepsi Can (330ml)",
        price: 59,
        itemId: "PH-20",
        img: "https://www.pizzahut.co.in/order/images/products/pepsi.png",
        isVeg: true,
        rating: 4.4,
        ratingCount: 890,
      },
      {
        name: "Indi Tandoori Pizza",
        price: 319,
        itemId: "PH-21",
        img: "https://www.pizzahut.co.in/order/images/products/indi_tandoori.png",
        isVeg: false,
        rating: 4.6,
        ratingCount: 815,
      },
      {
        name: "Zesty Veggie Pizza",
        price: 289,
        itemId: "PH-22",
        img: "https://www.pizzahut.co.in/order/images/products/zesty_veggie.png",
        isVeg: true,
        rating: 4.4,
        ratingCount: 760,
      },
      {
        name: "Classic Veg Pizza",
        price: 249,
        itemId: "PH-23",
        img: "https://www.pizzahut.co.in/order/images/products/classic_veg.png",
        isVeg: true,
        rating: 4.3,
        ratingCount: 700,
      },
      {
        name: "Peri Peri Chicken Pizza",
        price: 339,
        itemId: "PH-24",
        img: "https://www.pizzahut.co.in/order/images/products/peri_chicken.png",
        isVeg: false,
        rating: 4.5,
        ratingCount: 790,
      },
      {
        name: "Veggie Stuffed Crust",
        price: 359,
        itemId: "PH-25",
        img: "https://www.pizzahut.co.in/order/images/products/veggie_crust.png",
        isVeg: true,
        rating: 4.6,
        ratingCount: 850,
      },
    ],
  },
  {
    id: "res-tandori-hut-129",

    info: {
      resName: "Tandori Hut",
      resRating: 3.4,
      ratingsCount: 1995,
      startPrice: "Starts at Just Rs.119/-",
      deliveryTime: 40,
      deliveryCharges: 50,
      cuisineType: ["Hyderabadi", "Biryani"],
      availability: true,
      location: {
        city: "Hyderabad",
        area: "Gachibowli",
        pincode: "500032",
      },
      logoUrl: "https://example.com/logos/biryani-house.png",
    },
    offers: [
      {
        title: "Combo Meals from Rs.199/-",
        offerId: "th@01",
      },
    ],
    menuList: [
      {
        name: "Tandoori Chicken Full",
        price: 349,
        itemId: "TH-1",
        img: "https://www.cubesnjuliennes.com/wp-content/uploads/2020/12/Tandoori-Chicken-1.jpg",
        isVeg: false,
        rating: 4.7,
        ratingCount: 1140,
      },
      {
        name: "Tandoori Chicken Half",
        price: 199,
        itemId: "TH-2",
        img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/10/tandoori-chicken-recipe.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 980,
      },
      {
        name: "Paneer Tikka",
        price: 239,
        itemId: "TH-3",
        img: "https://www.cookingcarnival.com/wp-content/uploads/2021/02/Air-Fryer-Paneer-Tikka.jpg",
        isVeg: true,
        rating: 4.5,
        ratingCount: 875,
      },
      {
        name: "Chicken Seekh Kebab",
        price: 259,
        itemId: "TH-4",
        img: "https://www.archanaskitchen.com/images/archanaskitchen/1-Author/Shaheen_Ali/Chicken_Seekh_Kebab.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 925,
      },
      {
        name: "Veg Seekh Kebab",
        price: 199,
        itemId: "TH-5",
        img: "https://www.cookwithmanali.com/wp-content/uploads/2022/04/Veg-Seekh-Kabab.jpg",
        isVeg: true,
        rating: 4.4,
        ratingCount: 710,
      },
      {
        name: "Tandoori Mushroom",
        price: 229,
        itemId: "TH-6",
        img: "https://www.indianveggiedelight.com/wp-content/uploads/2020/11/tandoori-mushroom-featured.jpg",
        isVeg: true,
        rating: 4.5,
        ratingCount: 620,
      },
      {
        name: "Chicken Malai Tikka",
        price: 289,
        itemId: "TH-7",
        img: "https://www.whiskaffair.com/wp-content/uploads/2020/11/Chicken-Malai-Tikka-2-3.jpg",
        isVeg: false,
        rating: 4.7,
        ratingCount: 845,
      },
      {
        name: "Afghani Chicken",
        price: 329,
        itemId: "TH-8",
        img: "https://www.indianveggiedelight.com/wp-content/uploads/2021/10/afghani-chicken-featured.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 790,
      },
      {
        name: "Tandoori Fish Tikka",
        price: 309,
        itemId: "TH-9",
        img: "https://www.archanaskitchen.com/images/archanaskitchen/1-Author/Shaheen_Ali/Tandoori_Fish_Tikka_Recipe.jpg",
        isVeg: false,
        rating: 4.5,
        ratingCount: 615,
      },
      {
        name: "Stuffed Tandoori Aloo",
        price: 209,
        itemId: "TH-10",
        img: "https://www.cookwithmanali.com/wp-content/uploads/2016/01/Stuffed-Tandoori-Aloo-500x500.jpg",
        isVeg: true,
        rating: 4.4,
        ratingCount: 540,
      },
      {
        name: "Tandoori Prawns",
        price: 359,
        itemId: "TH-11",
        img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/02/tandoori-prawns.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 675,
      },
      {
        name: "Mixed Grill Platter",
        price: 499,
        itemId: "TH-12",
        img: "https://myfoodstory.com/wp-content/uploads/2021/07/Tandoori-Mixed-Grill-4.jpg",
        isVeg: false,
        rating: 4.8,
        ratingCount: 940,
      },
      {
        name: "Tandoori Veg Platter",
        price: 379,
        itemId: "TH-13",
        img: "https://www.whiskaffair.com/wp-content/uploads/2020/11/Veg-Tandoori-Platter-1.jpg",
        isVeg: true,
        rating: 4.5,
        ratingCount: 750,
      },
      {
        name: "Chicken Tangdi Kebab",
        price: 279,
        itemId: "TH-14",
        img: "https://www.cubesnjuliennes.com/wp-content/uploads/2020/12/Chicken-Tangdi-Kebab.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 720,
      },
      {
        name: "Tandoori Bhutta",
        price: 129,
        itemId: "TH-15",
        img: "https://www.cookingcarnival.com/wp-content/uploads/2020/08/Tandoori-Bhutta.jpg",
        isVeg: true,
        rating: 4.3,
        ratingCount: 530,
      },
      {
        name: "Hariyali Paneer Tikka",
        price: 249,
        itemId: "TH-16",
        img: "https://spicecravings.com/wp-content/uploads/2022/08/Hariyali-Paneer-Tikka-Featured.jpg",
        isVeg: true,
        rating: 4.6,
        ratingCount: 610,
      },
      {
        name: "Tandoori Roti",
        price: 25,
        itemId: "TH-17",
        img: "https://www.vegrecipesofindia.com/wp-content/uploads/2021/01/tandoori-roti-recipe.jpg",
        isVeg: true,
        rating: 4.4,
        ratingCount: 870,
      },
      {
        name: "Butter Naan",
        price: 39,
        itemId: "TH-18",
        img: "https://www.cookwithmanali.com/wp-content/uploads/2020/04/Butter-Naan.jpg",
        isVeg: true,
        rating: 4.6,
        ratingCount: 925,
      },
      {
        name: "Garlic Naan",
        price: 49,
        itemId: "TH-19",
        img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/11/garlic-naan-recipe.jpg",
        isVeg: true,
        rating: 4.7,
        ratingCount: 970,
      },
      {
        name: "Mint Raita",
        price: 59,
        itemId: "TH-20",
        img: "https://www.cookwithmanali.com/wp-content/uploads/2020/03/Mint-Raita.jpg",
        isVeg: true,
        rating: 4.4,
        ratingCount: 640,
      },
      {
        name: "Chicken Tandoori Roll",
        price: 199,
        itemId: "TH-21",
        img: "https://www.whiskaffair.com/wp-content/uploads/2020/08/Tandoori-Chicken-Roll-2.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 760,
      },
      {
        name: "Paneer Tandoori Wrap",
        price: 179,
        itemId: "TH-22",
        img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/09/paneer-kathi-roll.jpg",
        isVeg: true,
        rating: 4.5,
        ratingCount: 710,
      },
      {
        name: "Stuffed Kulcha",
        price: 89,
        itemId: "TH-23",
        img: "https://www.vegrecipesofindia.com/wp-content/uploads/2022/07/Paneer-Kulcha-2.jpg",
        isVeg: true,
        rating: 4.4,
        ratingCount: 820,
      },
      {
        name: "Tandoori Paratha",
        price: 69,
        itemId: "TH-24",
        img: "https://www.whiskaffair.com/wp-content/uploads/2020/11/Tandoori-Laccha-Paratha.jpg",
        isVeg: true,
        rating: 4.3,
        ratingCount: 610,
      },
      {
        name: "Lassi",
        price: 69,
        itemId: "TH-25",
        img: "https://www.vegrecipesofindia.com/wp-content/uploads/2021/06/sweet-lassi-1.jpg",
        isVeg: true,
        rating: 4.5,
        ratingCount: 690,
      },
    ],
  },
  {
    id: "res-sushi-house-130",
    info: {
      resName: "Sushi House",
      resRating: 4.3,
      ratingsCount: 1200,
      startPrice: "Starts at Just Rs.79/-",
      deliveryTime: 50,
      deliveryCharges: 25,
      cuisineType: ["Vegetarian", "Home Style"],
      availability: true,
      location: {
        city: "Pune",
        area: "Baner",
        pincode: "411045",
      },
      logoUrl: "https://example.com/logos/veggie-hut.png",
    },
    offers: [
      {
        title: "15% off on all vegetarian dishes",
        offerId: "ssh@1",
      },
    ],
    menuList: [
      {
        name: "California Roll",
        price: 249,
        itemId: "SH-1",
        img: "https://www.seriouseats.com/thmb/tWbJoF2M9gN4DAbC5TkYdQlD_8s=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20230124-California-Roll-Maki-Jennifer-Woodard-hero-02_1-2729ce4e50704cb98f04c37b3eb268eb.jpg",
        isVeg: false,
        rating: 4.7,
        ratingCount: 950,
      },
      {
        name: "Veg Futomaki Roll",
        price: 199,
        itemId: "SH-2",
        img: "https://www.justonecookbook.com/wp-content/uploads/2020/02/Futomaki-4508-I.jpg",
        isVeg: true,
        rating: 4.6,
        ratingCount: 620,
      },
      {
        name: "Salmon Nigiri",
        price: 229,
        itemId: "SH-3",
        img: "https://www.japanesecooking101.com/wp-content/uploads/2012/09/NigiriSushi.jpg",
        isVeg: false,
        rating: 4.8,
        ratingCount: 890,
      },
      {
        name: "Avocado Maki",
        price: 179,
        itemId: "SH-4",
        img: "https://www.acouplecooks.com/wp-content/uploads/2020/05/Avocado-Roll-005.jpg",
        isVeg: true,
        rating: 4.5,
        ratingCount: 500,
      },
      {
        name: "Tuna Sashimi",
        price: 299,
        itemId: "SH-5",
        img: "https://www.justonecookbook.com/wp-content/uploads/2019/08/Tuna-Sashimi.jpg",
        isVeg: false,
        rating: 4.9,
        ratingCount: 1050,
      },
      {
        name: "Ebi Tempura Roll",
        price: 269,
        itemId: "SH-6",
        img: "https://www.thespruceeats.com/thmb/Tm_KUnPbztAcRg_oqZc0a0xyW6c=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/EbiTempuraSushiRollGettyImages-1091183930-5bfc42d1c9e77c0058b0c54f.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 740,
      },
      {
        name: "Cucumber Maki",
        price: 159,
        itemId: "SH-7",
        img: "https://www.acouplecooks.com/wp-content/uploads/2020/05/Cucumber-Roll-005.jpg",
        isVeg: true,
        rating: 4.4,
        ratingCount: 430,
      },
      {
        name: "Rainbow Roll",
        price: 299,
        itemId: "SH-8",
        img: "https://www.thespruceeats.com/thmb/_gVxakV9nxzCRXIGfmuO4NofmjQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/rainbow-roll-sushi-2031526-hero-01-ccf8b38a4a2049b2be92ad05fae11e7c.jpg",
        isVeg: false,
        rating: 4.7,
        ratingCount: 790,
      },
      {
        name: "Tamago Nigiri",
        price: 209,
        itemId: "SH-9",
        img: "https://i.pinimg.com/736x/48/2c/d9/482cd93a233b6c407c82ec28aaf5dc13.jpg",
        isVeg: true,
        rating: 4.5,
        ratingCount: 470,
      },
      {
        name: "Spicy Tuna Roll",
        price: 259,
        itemId: "SH-10",
        img: "https://www.japanesecooking101.com/wp-content/uploads/2014/02/SpicyTunaRoll.jpg",
        isVeg: false,
        rating: 4.8,
        ratingCount: 910,
      },
      {
        name: "Unagi Roll",
        price: 289,
        itemId: "SH-11",
        img: "https://thejapaneseway.com/wp-content/uploads/2023/03/Unagi-sushi.webp",
        isVeg: false,
        rating: 4.6,
        ratingCount: 630,
      },
      {
        name: "Dragon Roll",
        price: 319,
        itemId: "SH-12",
        img: "https://www.thespruceeats.com/thmb/mS3h6bdIhVZKcNMQ5sJUlxrgFE8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/dragon-roll-2031527-hero-01-f7bcf9353cb64a4f8206b6b3cd4a41a6.jpg",
        isVeg: false,
        rating: 4.9,
        ratingCount: 970,
      },
      {
        name: "Edamame",
        price: 99,
        itemId: "SH-13",
        img: "https://www.cookingclassy.com/wp-content/uploads/2021/05/edamame-10.jpg",
        isVeg: true,
        rating: 4.5,
        ratingCount: 400,
      },
      {
        name: "Sushi Bento Box",
        price: 349,
        itemId: "SH-14",
        img: "https://japan.recipetineats.com/wp-content/uploads/2017/11/Sushi-Bento-3.jpg",
        isVeg: false,
        rating: 4.8,
        ratingCount: 860,
      },
      {
        name: "Miso Soup",
        price: 89,
        itemId: "SH-15",
        img: "https://www.acouplecooks.com/wp-content/uploads/2021/03/Miso-Soup-009.jpg",
        isVeg: true,
        rating: 4.4,
        ratingCount: 550,
      },
      {
        name: "Salmon Avocado Roll",
        price: 239,
        itemId: "SH-16",
        img: "https://i0.wp.com/thecollegehousewife.com/wp-content/uploads/2021/06/Salmon-Avocado-Sushi-Roll-15.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 690,
      },
      {
        name: "Tofu Nigiri",
        price: 189,
        itemId: "SH-17",
        img: "https://veganheaven.org/wp-content/uploads/2020/01/Inari-Sushi-3.jpg",
        isVeg: true,
        rating: 4.4,
        ratingCount: 310,
      },
      {
        name: "Shrimp Tempura Roll",
        price: 269,
        itemId: "SH-18",
        img: "https://thejapaneseway.com/wp-content/uploads/2023/03/Shrimp-tempura-roll.jpg",
        isVeg: false,
        rating: 4.7,
        ratingCount: 770,
      },
      {
        name: "Philadelphia Roll",
        price: 259,
        itemId: "SH-19",
        img: "https://www.justonecookbook.com/wp-content/uploads/2021/04/Philadelphia-Roll.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 640,
      },
      {
        name: "Seaweed Salad",
        price: 149,
        itemId: "SH-20",
        img: "https://www.acouplecooks.com/wp-content/uploads/2020/01/Seaweed-Salad-002.jpg",
        isVeg: true,
        rating: 4.5,
        ratingCount: 390,
      },
      {
        name: "Tako (Octopus) Nigiri",
        price: 289,
        itemId: "SH-21",
        img: "https://www.thesushigeek.com/wp-content/uploads/2021/04/Tako-Octopus-Nigiri.jpg",
        isVeg: false,
        rating: 4.7,
        ratingCount: 520,
      },
      {
        name: "Kanpyo Maki",
        price: 179,
        itemId: "SH-22",
        img: "https://www.japanesecooking101.com/wp-content/uploads/2015/02/KanpyoMaki.jpg",
        isVeg: true,
        rating: 4.3,
        ratingCount: 300,
      },
      {
        name: "Sashimi Platter",
        price: 429,
        itemId: "SH-23",
        img: "https://www.seriouseats.com/thmb/sYZG4rAcd3zNqWEDljh1c1JwA9E=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/platter-of-sashimi-58b7c6255f9b58af5c91c8b6.jpg",
        isVeg: false,
        rating: 4.9,
        ratingCount: 920,
      },
      {
        name: "Sweet Potato Roll",
        price: 189,
        itemId: "SH-24",
        img: "https://i.pinimg.com/564x/3d/dc/0a/3ddc0af41a3766a06e810f12c3912ac7.jpg",
        isVeg: true,
        rating: 4.4,
        ratingCount: 410,
      },
      {
        name: "Chashu Sushi",
        price: 299,
        itemId: "SH-25",
        img: "https://i.ytimg.com/vi/Zv8lFdfpVBA/maxresdefault.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 580,
      },
    ],
  },
  {
    id: "res-pasta-palace-131",
    info: {
      resName: "Pasta Palace",
      resRating: 4.3,
      ratingsCount: 880,
      startPrice: "Starts at Just Rs.139/-",
      deliveryTime: 45,
      deliveryCharges: 55,
      cuisineType: ["Continental", "Grill"],
      availability: false,
      location: {
        city: "Bengaluru",
        area: "Koramangala",
        pincode: "560034",
      },
      logoUrl: "https://example.com/logos/sizzler-street.png",
    },
    offers: [
      {
        title: "Free Dessert on order above 499/-",
        offerId: "pp@321",
      },
    ],
    menuList: [
      {
        name: "Spaghetti Bolognese",
        price: 299,
        itemId: "PP-1",
        img: "https://www.simplyrecipes.com/thmb/fWTIjb3AQE0F9O1f4_rjRz1a_R0=/2000x1333/filters:fill(auto,1)/Simply-Recipes-Spaghetti-Bolognese-LEAD-7-7a01e22cfe724cdbb46b3ce57c33d51a.jpg",
        isVeg: false,
        rating: 4.7,
        ratingCount: 1020,
      },
      {
        name: "Penne Arrabbiata",
        price: 249,
        itemId: "PP-2",
        img: "https://www.cookingclassy.com/wp-content/uploads/2018/04/penne-arrabbiata-13.jpg",
        isVeg: true,
        rating: 4.5,
        ratingCount: 850,
      },
      {
        name: "Fettuccine Alfredo",
        price: 279,
        itemId: "PP-3",
        img: "https://www.simplyrecipes.com/thmb/iLtA4AYNMequrGmK2M39KhBqX_U=/1500x1125/filters:fill(auto,1)/Simply-Recipes-Fettuccine-Alfredo-LEAD-03-bfe1d447ad5b4ac8a9e7774a9a25c27d.jpg",
        isVeg: true,
        rating: 4.6,
        ratingCount: 930,
      },
      {
        name: "Lasagna",
        price: 329,
        itemId: "PP-4",
        img: "https://www.simplyrecipes.com/thmb/E2__tjDmz-j1R7dEsl4HJ6VZoEk=/1500x1125/filters:fill(auto,1)/Simply-Recipes-Lasagna-LEAD-4-c183da12dbb241978e4f0f512a3861ca.jpg",
        isVeg: false,
        rating: 4.8,
        ratingCount: 1100,
      },
      {
        name: "Mac and Cheese",
        price: 229,
        itemId: "PP-5",
        img: "https://www.simplyrecipes.com/thmb/_O4-VmkgUqlHwtFtXoZa0SypcFw=/1500x1125/filters:fill(auto,1)/Simply-Recipes-Mac-Cheese-LEAD-04-bb4cc953bf0746c8b6f7bcecf85d5041.jpg",
        isVeg: true,
        rating: 4.4,
        ratingCount: 790,
      },
      {
        name: "Pasta Primavera",
        price: 269,
        itemId: "PP-6",
        img: "https://www.cookingclassy.com/wp-content/uploads/2019/02/pasta-primavera-9.jpg",
        isVeg: true,
        rating: 4.5,
        ratingCount: 680,
      },
      {
        name: "Seafood Linguine",
        price: 359,
        itemId: "PP-7",
        img: "https://www.simplyrecipes.com/thmb/Vj9RmWjuVd9p4vEU6yXK3j78xUc=/1500x1125/filters:fill(auto,1)/Simply-Recipes-Seafood-Linguine-LEAD-03-3db9e3c9aeed47f6a1687b71f34e4a1c.jpg",
        isVeg: false,
        rating: 4.7,
        ratingCount: 720,
      },
      {
        name: "Pesto Pasta",
        price: 259,
        itemId: "PP-8",
        img: "https://www.acouplecooks.com/wp-content/uploads/2020/05/Pesto-Pasta-005.jpg",
        isVeg: true,
        rating: 4.6,
        ratingCount: 820,
      },
      {
        name: "Chicken Alfredo Pasta",
        price: 329,
        itemId: "PP-9",
        img: "https://www.simplyrecipes.com/thmb/34x7huvTyGx3A5Uf8fYHT2bHqxI=/1500x1125/filters:fill(auto,1)/Simply-Recipes-Chicken-Alfredo-LEAD-04-88f0f0dbbd2a4cd193cbdb34c2b8e3e3.jpg",
        isVeg: false,
        rating: 4.7,
        ratingCount: 970,
      },
      {
        name: "Mushroom Ravioli",
        price: 299,
        itemId: "PP-10",
        img: "https://www.cookingclassy.com/wp-content/uploads/2019/01/mushroom-ravioli-5.jpg",
        isVeg: true,
        rating: 4.5,
        ratingCount: 610,
      },
      {
        name: "Baked Ziti",
        price: 319,
        itemId: "PP-11",
        img: "https://www.simplyrecipes.com/thmb/GrOdL8bzS5ZxNvl5PZhtnx4GHR0=/1500x1125/filters:fill(auto,1)/Simply-Recipes-Baked-Ziti-LEAD-4-7e25b73996244c24b951563d6371b2b3.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 720,
      },
      {
        name: "Spinach and Ricotta Cannelloni",
        price: 299,
        itemId: "PP-12",
        img: "https://www.cookingclassy.com/wp-content/uploads/2018/06/ricotta-spinach-cannelloni-21.jpg",
        isVeg: true,
        rating: 4.5,
        ratingCount: 690,
      },
      {
        name: "Garlic Breadsticks",
        price: 99,
        itemId: "PP-13",
        img: "https://www.simplyrecipes.com/thmb/RZRxu8XkPGlNFK2HKnWAKu0Uz6Y=/1500x1125/filters:fill(auto,1)/Simply-Recipes-Garlic-Breadsticks-LEAD-04-f683deaa737146a99d05488217e99a2f.jpg",
        isVeg: true,
        rating: 4.7,
        ratingCount: 890,
      },
      {
        name: "Caprese Salad",
        price: 189,
        itemId: "PP-14",
        img: "https://www.simplyrecipes.com/thmb/g9vVz__gH-lON01cswcNG8TbSiI=/1500x0/filters:no_upscale()/Simply-Recipes-Caprese-Salad-LEAD-01-c97b56146f99485a872f594d303ff2e9.jpg",
        isVeg: true,
        rating: 4.6,
        ratingCount: 700,
      },
      {
        name: "Pasta Carbonara",
        price: 299,
        itemId: "PP-15",
        img: "https://www.simplyrecipes.com/thmb/xglGxTYA6PvgSn3j1l_RxG7QG6k=/1500x1125/filters:fill(auto,1)/Simply-Recipes-Carbonara-LEAD-04-cc8d09b4e7a14b14a5e49b265e0a8c25.jpg",
        isVeg: false,
        rating: 4.7,
        ratingCount: 900,
      },
      {
        name: "Linguine with Clams",
        price: 339,
        itemId: "PP-16",
        img: "https://www.simplyrecipes.com/thmb/z8UEwL92_UZdEqk7KPR-yqNTHjs=/1500x1125/filters:fill(auto,1)/Simply-Recipes-Linguine-with-Clams-LEAD-03-02952c15727a42e9b0d13a503b5cc0ac.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 750,
      },
      {
        name: "Eggplant Parmesan Pasta",
        price: 279,
        itemId: "PP-17",
        img: "https://cookieandkate.com/images/2018/08/eggplant-parmesan-pasta-recipe-1.jpg",
        isVeg: true,
        rating: 4.5,
        ratingCount: 620,
      },
      {
        name: "Pasta Puttanesca",
        price: 279,
        itemId: "PP-18",
        img: "https://www.simplyrecipes.com/thmb/5nMwiXAoEMn9JcXb9ktOxLSWjz0=/1500x1125/filters:fill(auto,1)/Simply-Recipes-Puttanesca-LEAD-01-53eb8a8cda7446f89a3d3255b965a29e.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 710,
      },
      {
        name: "Cheese Stuffed Shells",
        price: 289,
        itemId: "PP-19",
        img: "https://cookieandkate.com/images/2016/08/cheese-stuffed-shells-recipe.jpg",
        isVeg: true,
        rating: 4.5,
        ratingCount: 630,
      },
      {
        name: "Shrimp Scampi Pasta",
        price: 349,
        itemId: "PP-20",
        img: "https://www.simplyrecipes.com/thmb/qFqooYy3t5cR6ZTHLkUHL8kbKx0=/1500x1125/filters:fill(auto,1)/Simply-Recipes-Shrimp-Scampi-LEAD-01-33c4d51738db49f3a8350ca60e1ed690.jpg",
        isVeg: false,
        rating: 4.7,
        ratingCount: 720,
      },
      {
        name: "Tomato Basil Penne",
        price: 249,
        itemId: "PP-21",
        img: "https://www.cookingclassy.com/wp-content/uploads/2018/04/penne-arrabbiata-13.jpg",
        isVeg: true,
        rating: 4.4,
        ratingCount: 560,
      },
    ],
  },
  {
    id: "res-biryani-by-kilo-132",
    info: {
      resName: "Biryani By Kilo",
      resRating: 4.4,
      ratingsCount: 2100,
      startPrice: "Starts at Just Rs.149/-",
      deliveryTime: 30,
      deliveryCharges: 45,
      cuisineType: ["Asian", "Thai", "Chinese"],
      availability: true,
      location: {
        city: "Delhi",
        area: "Saket",
        pincode: "110017",
      },
      logoUrl: "https://example.com/logos/asian-treats.png",
    },
    offers: [
      {
        title: "30% off on Pan-Asian menu",
        offerId: "bbk@01",
      },
    ],
    menuList: [
      {
        name: "Hyderabadi Chicken Biryani",
        price: 320,
        itemId: "BBK-1",
        img: "https://www.biryanibykilo.com/media/bkchickenbiryani.jpg",
        isVeg: false,
        rating: 4.8,
        ratingCount: 1500,
      },
      {
        name: "Lucknowi Mutton Biryani",
        price: 390,
        itemId: "BBK-2",
        img: "https://www.biryanibykilo.com/media/bkmuttonbiryani.jpg",
        isVeg: false,
        rating: 4.7,
        ratingCount: 1250,
      },
      {
        name: "Veg Biryani",
        price: 250,
        itemId: "BBK-3",
        img: "https://www.biryanibykilo.com/media/bkvegbiryani.jpg",
        isVeg: true,
        rating: 4.5,
        ratingCount: 900,
      },
      {
        name: "Chicken Tikka Biryani",
        price: 350,
        itemId: "BBK-4",
        img: "https://www.biryanibykilo.com/media/bcktikabiryani.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 1100,
      },
      {
        name: "Paneer Biryani",
        price: 280,
        itemId: "BBK-5",
        img: "https://www.biryanibykilo.com/media/bkpaneerbiryani.jpg",
        isVeg: true,
        rating: 4.4,
        ratingCount: 750,
      },
      {
        name: "Egg Biryani",
        price: 290,
        itemId: "BBK-6",
        img: "https://www.biryanibykilo.com/media/bkeggbiryani.jpg",
        isVeg: false,
        rating: 4.3,
        ratingCount: 700,
      },
      {
        name: "Kolkata Style Biryani",
        price: 340,
        itemId: "BBK-7",
        img: "https://www.biryanibykilo.com/media/bkkolkata.jpg",
        isVeg: false,
        rating: 4.7,
        ratingCount: 800,
      },
      {
        name: "Chicken 65 Biryani",
        price: 360,
        itemId: "BBK-8",
        img: "https://www.biryanibykilo.com/media/bkchicken65.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 950,
      },
      {
        name: "Mutton Keema Biryani",
        price: 400,
        itemId: "BBK-9",
        img: "https://www.biryanibykilo.com/media/bkkeemabiryani.jpg",
        isVeg: false,
        rating: 4.7,
        ratingCount: 670,
      },
      {
        name: "Veg Pulao",
        price: 220,
        itemId: "BBK-10",
        img: "https://www.biryanibykilo.com/media/bkvegpulao.jpg",
        isVeg: true,
        rating: 4.5,
        ratingCount: 820,
      },
      {
        name: "Mutton Shami Biryani",
        price: 410,
        itemId: "BBK-11",
        img: "https://www.biryanibykilo.com/media/bkshamibiryani.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 630,
      },
      {
        name: "Chicken Malai Biryani",
        price: 355,
        itemId: "BBK-12",
        img: "https://www.biryanibykilo.com/media/bkmalaibiryani.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 780,
      },
      {
        name: "Paneer Tikka Biryani",
        price: 300,
        itemId: "BBK-13",
        img: "https://www.biryanibykilo.com/media/bkpaneertikka.jpg",
        isVeg: true,
        rating: 4.4,
        ratingCount: 720,
      },
      {
        name: "Butter Chicken Biryani",
        price: 370,
        itemId: "BBK-14",
        img: "https://www.biryanibykilo.com/media/bkbutterchicken.jpg",
        isVeg: false,
        rating: 4.8,
        ratingCount: 1020,
      },
      {
        name: "Veg Fried Rice",
        price: 210,
        itemId: "BBK-15",
        img: "https://www.biryanibykilo.com/media/bkvegfriedrice.jpg",
        isVeg: true,
        rating: 4.3,
        ratingCount: 560,
      },
      {
        name: "Chicken Fried Rice",
        price: 280,
        itemId: "BBK-16",
        img: "https://www.biryanibykilo.com/media/bkchickenfriedrice.jpg",
        isVeg: false,
        rating: 4.5,
        ratingCount: 600,
      },
      {
        name: "Mutton Biryani Plate",
        price: 390,
        itemId: "BBK-17",
        img: "https://www.biryanibykilo.com/media/bkmuttonplate.jpg",
        isVeg: false,
        rating: 4.7,
        ratingCount: 890,
      },
      {
        name: "Chicken Hyderabadi Plate",
        price: 330,
        itemId: "BBK-18",
        img: "https://www.biryanibykilo.com/media/bkchickenplate.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 870,
      },
      {
        name: "Veg Korma",
        price: 270,
        itemId: "BBK-19",
        img: "https://www.biryanibykilo.com/media/bkvegkorma.jpg",
        isVeg: true,
        rating: 4.4,
        ratingCount: 520,
      },
      {
        name: "Chicken Korma",
        price: 320,
        itemId: "BBK-20",
        img: "https://www.biryanibykilo.com/media/bkchickenkorma.jpg",
        isVeg: false,
        rating: 4.6,
        ratingCount: 580,
      },
      {
        name: "Raita Bowl",
        price: 80,
        itemId: "BBK-21",
        img: "https://www.biryanibykilo.com/media/bkraita.jpg",
        isVeg: true,
        rating: 4.2,
        ratingCount: 340,
      },
      {
        name: "Chicken Shorba",
        price: 120,
        itemId: "BBK-22",
        img: "https://www.biryanibykilo.com/media/bkchickenshorba.jpg",
        isVeg: false,
        rating: 4.5,
        ratingCount: 410,
      },
      {
        name: "Veg Seekh Kebab",
        price: 250,
        itemId: "BBK-23",
        img: "https://www.biryanibykilo.com/media/bkvegseekhkebab.jpg",
        isVeg: true,
        rating: 4.3,
        ratingCount: 290,
      },
      {
        name: "Chicken Seekh Kebab",
        price: 270,
        itemId: "BBK-24",
        img: "https://www.biryanibykilo.com/media/bkchickenseekh.jpg",
        isVeg: false,
        rating: 4.5,
        ratingCount: 400,
      },
      {
        name: "Gulab Jamun",
        price: 100,
        itemId: "BBK-25",
        img: "https://www.biryanibykilo.com/media/bkgulabjamun.jpg",
        isVeg: true,
        rating: 4.7,
        ratingCount: 720,
      },
    ],
  },
];
export default menuData;
